### ISSUE TITLE
error unitialized deck 

### ISSUE THREAD

**Issue by fishtez** [fishtez/blackjack#3]
if the player doesnt first both generate and shuffle a deck, they can't play. can we adjust the code so that it creates and shuffles a deck before the menu displays? or simply display an error message if they try to play without first BOTH creating and shuffling the deck.

![error uninitialized deck](https://cloud.githubusercontent.com/assets/12114756/7443687/04878df0-f114-11e4-842e-b210b7cafeec.png)

**Comment by DavidL47** [comment]
yea we should probably just generate a new deck before the menu display

**Comment by DavidL47** [comment]
Fixed it I just made a new deck at the very beginning of the game before the menu

**Comment by Zubz21** [comment]
Ok so i have play as a function now which returns winOrLoss which means
wager works.

However i am still getting the same menu problem where it will not loop me
back to continue playing game.

Also i feel like if wager returns wallet then it will update the wallet.

**Comment by DavidL47** [comment]
just fixed it in the updated one

**Comment by DavidL47** [comment]
now we gotta worry about when it runs out of cards

**Comment by fishtez** [comment]
Wager is a void function, but wallet is passed in by reference, so it gets updated
